const String site="";


const String aboutTumor='A tumor, also known as a neoplasm, is an abnormal growth of cells that can develop in any part of the body. Tumors can be benign (not cancerous) or malignant (cancerous). Benign tumors do not spread to other parts of the body and are not usually life-threatening, while malignant tumors can invade nearby tissues and organs and spread to other parts of the body through the bloodstream or lymphatic system, potentially leading to serious health problems and even death if left untreated. The causes of tumors are complex and can involve genetic mutations, environmental factors, and lifestyle choices.';

const String aboutGiloma='Glioma is a growth of cells that starts in the brain or spinal cord. The cells in a glioma look similar to healthy brain cells called glial cells. Glial cells surround nerve cells and help them function.As a glioma grows it forms a mass of cells called a tumor. The tumor can grow to press on brain or spinal cord tissue and cause symptoms. Symptoms depend on which part of the brain or spinal cord is affected.There are many types of glioma. Some grow slowly and aren\'t considered to be cancers. Others are considered cancerous. Another word for cancerous is malignant. Malignant gliomas grow quickly and can invade healthy brain tissue. Some types of glioma happen mostly in adults. Others happen mostly in kids.The type of glioma you have helps your health care team understand how serious your condition is and what treatments might work best.';
const String gilomaCauses='Doctors aren\'t sure what causes glioma. It starts when cells in the brain or spinal cord develop changes in their DNA. A cell\'s DNA contains the instructions that tell a cell what to do.The DNA changes tell the cells to make more cells quickly. The cells continue living when healthy cells would die. This causes too many cells that don\'t work right. The cells form a mass called a tumor.The tumor can grow to press on nearby nerves and parts of the brain or spinal cord. This leads to glioma symptoms and can cause complications.Some gliomas develop more changes in their DNA that cause them to become brain cancers. The changes tell the cells to invade and destroy healthy brain tissue.In glioma, the tumor cells look similar to healthy brain cells called glial cells. The glial cells surround and support nerve cells in the brain and spinal cord.';



const String aboutPituitary='A pituitary tumor is an abnormal growth of cells within the pituitary gland.The pituitary gland is a small, bean-sized gland located at the base of the brain below the hypothalamus. The pituitary gland controls a system of hormones in the body that regulate growth, metabolism, the stress response, and functions of the sex organs via the thyroid gland, adrenal gland, ovaries, and testes.Most pituitary tumors are benign, which means they are non-cancerous, grow slowly, and do not spread to other parts of the body. However, the tumors can make the pituitary gland produce either too many or too few hormones, which can cause a variety of problems in the body. Symptoms largely depend upon the hormone affected and may include:\nHeadaches. \nVision problems. \nNausea. \nVomiting.';




const String findPituitary='Information may be available from the following resources:\nAmerican Brain Tumor Association (ABTA)\nNational Brain Tumor Society\nNational Institute of Child Health and Human Development (NICHD)\nNational Institute of Diabetes and Digestive and Kidney Diseases (NIDDK)\nPituitary Network Association';



const String aboutMeningioma='Meningioma grades are based on the tumor location, meningioma type, spread and potential for the tumor to remain after surgery. Meningiomas may require molecular testing to determine its grade.Grade I are the most common and are low-grade tumors with slow-growing cellsGrade II are mid-grade atypical meningiomas with a greater chance of returning after removal. Subtypes include choroid and clear cell meningiomaGrade III are anaplastic malignant tumors that are fast-growing and include papillary and rhabdoid meningiomaThe World Health Organization (WHO) also classifies brain tumors, highlighting 15 variations of meningiomas based on cell type. The meningioma WHO grading system includes atypical meningiomas in WHO Grade II and anaplastic malignant tumors in WHO Grade III.';

const String treatmentMeningioma='Meningioma treatment plans vary based on tumor size, location, growth rate, association with neurologic symptoms, as well as the patient’s age and overall health. Meningioma treatment includes three options:Observation for small tumors not causing symptoms. Patients will have regular CT or MRI scans to monitor for tumor growthSurgery to remove the tumor. The goal is to remove the entire tumor and the membranes from which it originates. Complexity of the surgery depends on the tumor’s location and involved nerves and blood vesselsRadiation may be used in combination with surgery to treat patients with aggressive meningiomas';



